"""initial schema

Revision ID: 18e39188719b
Revises: 
Create Date: 2026-04-30 16:03:59.921985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '18e39188719b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clerk_user_id', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('plan', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_user_id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'dispatched', 'processing', 'completed', 'failed', 'cancelled', 'expired', name='job_status'), nullable=False),
    sa.Column('claim_token', sa.UUID(), nullable=True),
    sa.Column('input_s3_key', sa.Text(), nullable=False),
    sa.Column('input_hash', sa.Text(), nullable=True),
    sa.Column('input_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_s3_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_stage', sa.Text(), nullable=True),
    sa.Column('progress_pct', sa.SmallInteger(), nullable=True),
    sa.Column('failure_class', sa.Enum('user_content', 'user_quota', 'system_transient', 'system_permanent', 'timeout', 'cancelled', name='failure_class'), nullable=True),
    sa.Column('failure_code', sa.Text(), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('failure_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('dispatched_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_jobs_expires', 'jobs', ['expires_at'], unique=False, postgresql_where="status != 'expired'")
    op.create_index('idx_jobs_queued', 'jobs', ['created_at'], unique=False, postgresql_where="status = 'queued'")
    op.create_index('idx_jobs_user_created', 'jobs', ['user_id', 'created_at'], unique=False)
    op.create_table('quotas',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('max_concurrent_jobs', sa.Integer(), nullable=False),
    sa.Column('max_minutes_per_month', sa.Integer(), nullable=False),
    sa.Column('max_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('minutes_used_this_month', sa.Integer(), nullable=False),
    sa.Column('quota_reset_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('idempotency_keys',
    sa.Column('key', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('request_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('job_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('from_status', sa.Enum('queued', 'dispatched', 'processing', 'completed', 'failed', 'cancelled', 'expired', name='job_status'), nullable=True),
    sa.Column('to_status', sa.Enum('queued', 'dispatched', 'processing', 'completed', 'failed', 'cancelled', 'expired', name='job_status'), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('read_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('emailed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_table('job_events')
    op.drop_table('idempotency_keys')
    op.drop_table('quotas')
    op.drop_index('idx_jobs_user_created', table_name='jobs')
    op.drop_index('idx_jobs_queued', table_name='jobs', postgresql_where="status = 'queued'")
    op.drop_index('idx_jobs_expires', table_name='jobs', postgresql_where="status != 'expired'")
    op.drop_table('jobs')
    op.drop_table('users')
    # ### end Alembic commands ###
