"""add_folders_and_transcript_text

Revision ID: b99f0c4c6dde
Revises: e1f2a3b4c5d6
Create Date: 2026-05-04 13:14:27.339119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b99f0c4c6dde'
down_revision: Union[str, Sequence[str], None] = 'e1f2a3b4c5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('jobs', sa.Column('folder_id', sa.UUID(), nullable=True))
    op.add_column('jobs', sa.Column('transcript_text', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'folders', ['folder_id'], ['id'], ondelete='CASCADE')
    # GIN index for full-text search on transcript_text
    op.execute(
        "CREATE INDEX idx_jobs_transcript_fts ON jobs "
        "USING GIN (to_tsvector('english', COALESCE(transcript_text, '')))"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS idx_jobs_transcript_fts")
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'transcript_text')
    op.drop_column('jobs', 'folder_id')
    op.drop_table('folders')
    # ### end Alembic commands ###
